### PR TITLE
Implementing Godotris

### PR DESCRIPTION
**Pull request by MrakDun-desu**
Added a new little game, based off classic Tetris! Scoring is the same, but random piece generation is quite a bit less strict and movement should also be little bit faster.
Game is just ~35kB, so hopefully no problems with the size there. Also doesn't use any autoloads.

### CODE REVIEW

**Comment by popcar2** [comment]
This is great! Thanks for your contribution! The code looks good, and the game seems to work flawlessly.

Can you add a button to slam the piece down if the player presses spacebar? It should just drop the piece as much as possible in the same frame then spawn the next piece on the next frame.

I also think the red background looks a little menacing, maybe a cooler gradient or flat color can be easier on the eyes. I can change the theme later on myself if you don't want to. Thanks!

**Comment by MrakDun-desu** [comment]
Changed the background to a cooler color, also spacebar now does harddrop! Also also, added a label with controls, just to make sure players will know what they can do in the game and how.

**Comment by popcar2** [comment]
One final nitpick: Hard dropping doesn't provide any score while soft dropping does. Other than that, looks good and I'm ready to merge as soon as it's fixed 👍

**Comment by MrakDun-desu** [comment]
Forgot about that, thanks for reminder! Now it should be ready.

**Comment by popcar2** [comment]
Thanks! I'll add your name to the credits, with new builds to come soon.

**Pull request merged**
