### PR TITLE
Add simple snake game

### PR DESCRIPTION
**Pull request by jean-philippe-martin**
This pull request adds a simple "snake" game. The folder takes only 16Kb and the game is playable, complete with a score counter.

It also adds it to the taskbar so it can be started via the OS interface.

Screen Shot 2024-01-21 at 5 37 33 PM

### CODE REVIEW

**Comment by popcar2** [comment]
I played around a bit, and it's pretty fun! Thanks for the PR.

Some notes though before I can merge it:

* Hitting a wall causes an error: `SnakeBoard.gd:116 @ tick(): Index p_x = 64 is out of bounds (width = 64).`, this needs to be handled else it'll crash GodotOS when exported.
* There are some old commented code like in SnakeBoard line 125 that should be removed. Print statements on death should also be removed.
* The score counter doesn't reset when you play again.
* Use RichTextLabel nodes instead of Label, then go down to theme overrides in the inspector to set font size. Currently the text looks crusty when the window is maximized because of this.
* Can you center the game over screen and make the restart button bigger? Something like what Godotris has.
* Can you also reduce the bezel on the right side of the screen? It's a bit odd that the game isn't centered in the window. 

Lastly, this is just my opinion but I think the game's a bit too fast which makes micromovements hard and getting fruits that spawn on the edge a bit too punishing. I think a `time_per_tick` of 1.0/20.0 would be a lot nicer.

image

**Comment by jean-philippe-martin** [comment]
Thank you for your detailed feedback! 

I have applied all your suggestions:

- fix error on wall hit
- remove commented-out code
- reset score counter on game restart
- switch to RichTextLabel and scale=1
- center "game over" screen
- make restart button bigger
- center the playing board, make it wider to reduce the bezel
- slow down snake

 and also added a few gameplay improvements:

- add high score display
- hide mouse while playing (unless it's moved)
- snake speeds up every 50 points
- apples always appear a little away from the edge
- added logic to make sure the apple always appears, even if the snake basically fills the screen.

It's ready for you to take a second look!

**Comment by popcar2** [comment]
Thanks for the update! Looks good to me, and I really like that apples don't appear directly on the edge anymore. I'll do some minor cleanup after merging then release a new build soon.

**Comment by jean-philippe-martin** [comment]
Fantastic, thank you very much!

**Pull request merged**
